spring.application.name=spring_project

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# MongoDB Configuration
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://${MONGO_USERNAME:doronmerioz12_db_user}:${MONGO_PASSWORD:Avatar291103}@avatar.wqfum3r.mongodb.net/postgres?retryWrites=true&w=majority&appName=Avatar}

# Application Security Configuration
app.security.user.username=${SECURITY_USER_NAME:driver}
app.security.user.password=${SECURITY_USER_PASSWORD:drive123}
app.security.admin.username=${SECURITY_ADMIN_NAME:manager}
app.security.admin.password=${SECURITY_ADMIN_PASSWORD:boss2026}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true